
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 20 14:34:39 IST 2015
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LENG = 23;
  public static final int DIVIDE = 9;
  public static final int LCBR = 21;
  public static final int LTE = 26;
  public static final int INTEGER = 50;
  public static final int SEMI = 36;
  public static final int CONTINUE = 8;
  public static final int INT = 18;
  public static final int MINUS = 27;
  public static final int STATIC = 37;
  public static final int LT = 25;
  public static final int LP = 2;
  public static final int COMMA = 7;
  public static final int CLASS = 38;
  public static final int READI = 46;
  public static final int RP = 3;
  public static final int PLUS = 32;
  public static final int MULTIPLY = 29;
  public static final int ASSIGN = 4;
  public static final int IF = 17;
  public static final int THIS = 39;
  public static final int DOT = 10;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int RETURN = 35;
  public static final int RCBR = 34;
  public static final int LB = 20;
  public static final int LAND = 19;
  public static final int EQUAL = 11;
  public static final int TRUE = 40;
  public static final int error = 1;
  public static final int RB = 33;
  public static final int LOR = 24;
  public static final int NULL = 31;
  public static final int NUMBER = 48;
  public static final int MOD = 28;
  public static final int IDENT = 45;
  public static final int BREAK = 6;
  public static final int VOID = 41;
  public static final int GTE = 16;
  public static final int ELSE = 14;
  public static final int WHILE = 42;
  public static final int NEQUAL = 30;
  public static final int CLASS_ID = 44;
  public static final int EXTENDS = 12;
  public static final int STRING = 43;
  public static final int FALSE = 13;
  public static final int GT = 15;
  public static final int VAR = 49;
  public static final int PRINT = 47;
  public static final int LENGTH = 22;
}

