
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 20 10:31:02 IST 2015
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LT = 11;
  public static final int PAHASHPA = 16;
  public static final int PLUS = 2;
  public static final int RPAREN = 7;
  public static final int LOR = 15;
  public static final int SEMI = 8;
  public static final int LPAREN = 6;
  public static final int GT = 10;
  public static final int LAND = 14;
  public static final int LE = 13;
  public static final int READI = 17;
  public static final int NUMBER = 19;
  public static final int EOF = 0;
  public static final int MULT = 4;
  public static final int DIV = 5;
  public static final int GE = 12;
  public static final int MINUS = 3;
  public static final int PRINT = 18;
  public static final int error = 1;
  public static final int ASSIGN = 9;
  public static final int INTEGER = 21;
  public static final int VAR = 20;
}

