
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 29 01:04:10 IDT 2015
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 18;
  public static final int LCBR = 24;
  public static final int LTE = 22;
  public static final int UMINUS = 48;
  public static final int INTEGER = 2;
  public static final int CONTINUE = 36;
  public static final int SEMI = 12;
  public static final int INT = 45;
  public static final int MINUS = 16;
  public static final int STATIC = 44;
  public static final int LT = 21;
  public static final int LP = 14;
  public static final int COMMA = 31;
  public static final int CLASS = 35;
  public static final int RP = 11;
  public static final int PLUS = 15;
  public static final int MULTIPLY = 17;
  public static final int ASSIGN = 33;
  public static final int QUOTE = 3;
  public static final int IF = 32;
  public static final int THIS = 41;
  public static final int DOT = 13;
  public static final int BOOLEAN = 47;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int RCBR = 25;
  public static final int LB = 23;
  public static final int LAND = 28;
  public static final int EQUAL = 10;
  public static final int TRUE = 7;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int RB = 26;
  public static final int LOR = 29;
  public static final int NULL = 49;
  public static final int MOD = 30;
  public static final int BREAK = 34;
  public static final int IDENT = 4;
  public static final int VOID = 42;
  public static final int GTE = 20;
  public static final int ELSE = 38;
  public static final int WHILE = 43;
  public static final int NEQUAL = 9;
  public static final int CLASS_ID = 5;
  public static final int EXTENDS = 37;
  public static final int STRING = 46;
  public static final int LNEG = 27;
  public static final int FALSE = 6;
  public static final int GT = 19;
  public static final int LENGTH = 8;
}

